# Makefile untuk program validasi ekspresi matematika

CC = gcc
CFLAGS = -Wall -Wextra

SRCS = LinkedList.c Stack.c Queue.c MathExpressionValidator.c main.c
OBJS = $(SRCS:.c=.o)
TARGET = validator

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(TARGET)

run: $(TARGET)
	./$(TARGET)
